Repository Automattic/wordpress-rs, pull requests merged in 2024-08, with the labels that each got.

#230 Condense error variants into `WpError`
  native/kotlin/api/android/src/androidTest/kotlin/rs/wordpress/api/android/UsersEndpointAndroidTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/ApiUrlDiscoveryTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/ApplicationPasswordsEndpointTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/IntegrationTestHelpers.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/PluginsEndpointTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/PostTypesEndpointTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/UsersEndpointTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/WpSiteHealthTestsEndpointTest.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpApiClient.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpRequestResult.kt
  wp_api/src/api_error.rs
  wp_api/src/lib.rs
  wp_api/src/request.rs
  wp_api_integration_tests/src/lib.rs
  wp_api_integration_tests/tests/test_application_passwords_err.rs
  wp_api_integration_tests/tests/test_plugins_err.rs
  wp_api_integration_tests/tests/test_post_types_err.rs
  wp_api_integration_tests/tests/test_users_err.rs
Labels: Kotlin, Rust, Error Handling

#104 Run Integration Tests in CI
  .buildkite/pipeline.yml
  Cargo.lock
  Makefile
  docker-compose.yml
  scripts/restore-test-server.sh
  scripts/run-integration-tests.sh
  scripts/setup-test-site.sh
  wp_api_integration_tests/Cargo.toml
  wp_api_integration_tests/src/fs_utils.rs
  wp_api_integration_tests/src/lib.rs
  wp_api_integration_tests/src/main.rs
  wp_api_integration_tests/src/wp_cli.rs
  wp_api_integration_tests/src/wp_db.rs
  wp_api_integration_tests/tests/test_login_immut.rs
  wp_api_integration_tests/tests/test_site_settings_mut.rs
Labels: Rust, Testing

#234 Update Kotlin wrapper to fix breaking changes
  native/kotlin/api/kotlin/src/integrationTest/kotlin/SiteSettingsEndpointTest.kt
  native/kotlin/example/composeApp/src/commonMain/kotlin/rs/wordpress/example/shared/ui/plugins/PluginListViewModel.kt
  native/kotlin/example/composeApp/src/commonMain/kotlin/rs/wordpress/example/shared/ui/users/UserListViewModel.kt
Labels: Kotlin

#235 Publishing Kotlin artifacts no longer depends on Detekt
  .buildkite/pipeline.yml
Labels: Tooling

#236 Remove unnecessary JNI configuration
  native/kotlin/api/android/build.gradle.kts
Labels: Tooling, Kotlin

#238 Remove native cargo target from `:api:android` Kotlin module
  native/kotlin/api/android/build.gradle.kts
Labels: Tooling, Kotlin

#240 Document `make setup-rust`
  Makefile
Labels: Documentation

#241 Update Gems to address rexml vulnerability
  Gemfile.lock
Labels: Bug, dependency

#239 Change url discovery `attempts` type from `Vec` to `HashMap`
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api_integration_tests/src/lib.rs
Labels: Rust

#243 Update `CHANGELOG` in preparation of `0.2` release
  CHANGELOG.md
Labels: Documentation

#247 Add response status code to `FetchApiRootUrlError.ApiRootLinkHeaderNotFound`
  wp_api/src/login/url_discovery.rs
Labels: Rust, Error Handling

#246 Kotlin integration tests in Docker & CI
  .buildkite/pipeline.yml
  Makefile
  docker-compose.yml
  scripts/run-kotlin-integration-tests.sh
  scripts/run-rust-integration-tests.sh
  scripts/setup-test-site.sh
  wordpress.Dockerfile
Labels: Tooling, Kotlin, Rust

#248 Remove `androidx-annotation` Kotlin dependency
  native/kotlin/api/android/build.gradle.kts
  native/kotlin/gradle/libs.versions.toml
Labels: Kotlin

#244 Enable url discovery tests for `automatticwidgets.wpcomstaging.com`
  wp_api_integration_tests/tests/test_login_immut.rs
Labels: Rust, Testing

#249 Print Kotlin integration test results and report them to Buildkite Test Analytics
  .buildkite/commands/run-kotlin-integration-tests.sh
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
  native/kotlin/api/kotlin/build.gradle.kts
Labels: Tooling, Kotlin

#251 Add CodeQL
  .github/workflows/codeql.yml
Labels: Tooling

#259 Integration tests backend support
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  docker-compose.yml
  scripts/restore-test-server.sh
  scripts/start-wp-api-integration-tests-backend.sh
  wp_api/Cargo.toml
  wp_api/src/lib.rs
  wp_api/src/login.rs
  wp_api_integration_tests/Cargo.toml
  wp_api_integration_tests/src/backend.rs
  wp_api_integration_tests/src/fs_utils.rs
  wp_api_integration_tests/src/lib.rs
  wp_api_integration_tests/src/main.rs
  wp_api_integration_tests/src/wp_db.rs
  wp_api_integration_tests/tests/test_application_passwords_mut.rs
  wp_api_integration_tests/tests/test_plugins_mut.rs
  wp_api_integration_tests/tests/test_site_settings_mut.rs
  wp_api_integration_tests/tests/test_users_mut.rs
  wp_api_integration_tests_backend/Cargo.toml
  wp_api_integration_tests_backend/src/main.rs
  wp_cli/Cargo.toml
  wp_cli/src/lib.rs
  wp_cli/src/wp_cli_settings.rs
  wp_cli/src/wp_cli_users.rs
  wp_serde_helper/Cargo.toml
  wp_serde_helper/src/lib.rs
Labels: Tooling, Rust, Testing

#261 Helper script to kickstart a new endpoint implementation
  scripts/new-endpoint.sh
Labels: Tooling

#263 Remove `sqlx` dependency and restore db with `wp_cli`
  Cargo.lock
  Cargo.toml
  wp_api_integration_tests/Cargo.toml
  wp_api_integration_tests_backend/Cargo.toml
  wp_api_integration_tests_backend/src/main.rs
  wp_cli/src/lib.rs
Labels: Rust, Testing, dependency

#264 List `/posts` endpoint
  wp_api/src/api_client.rs
  wp_api/src/lib.rs
  wp_api/src/posts.rs
  wp_api/src/request/endpoint.rs
  wp_api/src/request/endpoint/posts_endpoint.rs
  wp_api_integration_tests/tests/test_posts_immut.rs
Labels: Rust, Endpoint, Testing

#266 `AppendUrlQueryPairs` & `QueryPairsExtension` traits
  wp_api/src/lib.rs
  wp_api/src/plugins.rs
  wp_api/src/posts.rs
  wp_api/src/request/endpoint/users_endpoint.rs
  wp_api/src/unit_test_common.rs
  wp_api/src/url_query.rs
  wp_api/src/users.rs
  wp_derive_request_builder/src/generate.rs
  wp_derive_request_builder/src/generate/helpers_to_generate_tokens.rs
Labels: Rust

#275 Retrieve `/posts` endpoint
  scripts/setup-test-site.sh
  wp_api/src/api_error.rs
  wp_api/src/posts.rs
  wp_api/src/request/endpoint/posts_endpoint.rs
  wp_api_integration_tests/src/lib.rs
  wp_api_integration_tests/tests/test_posts_err.rs
  wp_api_integration_tests/tests/test_posts_immut.rs
Labels: Rust, Endpoint, Error Handling, Testing

#276 Add `additional_query_pairs` support for `#[derive(WpDerivedRequest)]`
  CHANGELOG.md
  wp_api/src/request/endpoint.rs
  wp_derive_request_builder/src/generate.rs
  wp_derive_request_builder/src/generate/helpers_to_generate_tokens.rs
Labels: Rust

#277 Implement delete & trash `/posts` endpoint and their integration tests
  wp_api/src/posts.rs
  wp_api/src/request/endpoint/posts_endpoint.rs
  wp_api_integration_tests/src/backend.rs
  wp_api_integration_tests/tests/test_posts_mut.rs
  wp_api_integration_tests_backend/src/main.rs
  wp_cli/src/lib.rs
  wp_cli/src/wp_cli_posts.rs
Labels: Rust, Endpoint, Testing

#278 Add missing `#[parallel]` attribute to integration tests
  wp_api_integration_tests/tests/test_login_immut.rs
  wp_api_integration_tests/tests/test_plugins_err.rs
  wp_api_integration_tests/tests/test_users_err.rs
Labels: Rust, Testing
