Repository Automattic/wordpress-rs, pull requests merged in 2025-02, with the labels that each got.

#522 Address Kotlin breaking changes in api discovery and RequestExecutionError
  native/kotlin/api/kotlin/src/integrationTest/kotlin/ApiUrlDiscoveryTest.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpApiClient.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpLoginClient.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpRequestResult.kt
Labels: Kotlin, Login

#523 Update Rust to 1.84.1
  Makefile
Labels: Rust

#530 Parallelize fetching & parsing plugin directory test
  Cargo.lock
  Cargo.toml
  wp_api_integration_tests/Cargo.toml
  wp_api_integration_tests/tests/test_plugin_directory.rs
Labels: Rust, Testing

#514 Rework auto discovery experience
  Cargo.lock
  Cargo.toml
  Package.resolved
  Package.swift
  native/kotlin/api/kotlin/src/integrationTest/kotlin/ApiUrlDiscoveryTest.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpApiClient.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpLoginClient.kt
  native/kotlin/api/kotlin/src/main/kotlin/rs/wordpress/api/kotlin/WpRequestResult.kt
  native/swift/Sources/wordpress-api/Exports.swift
  native/swift/Sources/wordpress-api/LoginAPI.swift
  native/swift/Sources/wordpress-api/SafeRequestExecutor.swift
  native/swift/Sources/wordpress-api/WordPressAPI.swift
  native/swift/Sources/wordpress-api/WordPressLoginClientError.swift
  native/swift/Tests/wordpress-api/Endpoints/Users.swift
  native/swift/Tests/wordpress-api/HTTPErrorTests.swift
  native/swift/Tests/wordpress-api/LoginTests.swift
  native/swift/Tests/wordpress-api/Support/Extensions.swift
  native/swift/Tests/wordpress-api/Support/HTTPStubs.swift
  native/swift/Tests/wordpress-api/WordPressAPITests.swift
  wp_api/Cargo.toml
  wp_api/src/api_error.rs
  wp_api/src/lib.rs
  wp_api/src/login.rs
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api/src/parsed_url.rs
  wp_api/src/request.rs
  wp_api/src/ssl.rs
  wp_api/src/wordpress_org/client.rs
  wp_api/src/wordpress_org/update_check.rs
  wp_api_integration_tests/src/lib.rs
  wp_api_integration_tests/tests/test_login_err.rs
  wp_api_integration_tests/tests/test_login_immut.rs
  wp_api_integration_tests/tests/test_media_err.rs
Labels: Swift, Kotlin, Rust, Error Handling, Testing, Login

#534 Running CodeQL on every PR takes forever
  .github/workflows/codeql.yml
Labels: Tooling

#536 Implement `is_wordpress_site` for api discovery
  Cargo.lock
  Cargo.toml
  wp_api/Cargo.toml
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api_integration_tests/tests/test_login_immut.rs
Labels: Rust, Testing, Login

#537 Combine `is_wordpress_site` with api discovery
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api_integration_tests/tests/test_login_err.rs
  wp_api_integration_tests/tests/test_login_immut.rs
Labels: Rust, Testing

#541 Don't require importing `AsQueryValue` from `impl_as_query_value_from_to_string` macro
  wp_api/src/categories.rs
  wp_api/src/comments.rs
  wp_api/src/lib.rs
  wp_api/src/media.rs
  wp_api/src/plugins.rs
  wp_api/src/post_types.rs
  wp_api/src/posts.rs
  wp_api/src/search_results.rs
  wp_api/src/tags.rs
  wp_api/src/templates.rs
  wp_api/src/themes.rs
  wp_api/src/url_query.rs
  wp_api/src/users.rs
Labels: Rust

#542 Don't allow `dead_code` or `unused_variables`
  wp_api/src/api_error.rs
  wp_api/src/lib.rs
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api/src/request.rs
  wp_api/src/request/endpoint.rs
  wp_api/src/request/endpoint/categories_endpoint.rs
  wp_api/src/request/endpoint/media_endpoint.rs
  wp_api/src/request/endpoint/tags_endpoint.rs
  wp_api/src/ssl.rs
  wp_api/src/url_query.rs
  wp_api/src/wordpress_org/plugin_directory.rs
Labels: Rust

#538 Improve constructed attempts for api discovery and handle parsing link tag for api root url
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api_integration_tests/tests/test_login_immut.rs
Labels: Rust, Testing, Login

#548 Add missing `API_ROOT_LINK_HEADER` to `url_discovery` mod
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
Labels: Rust

#549 Add `https` auto discovery attempt for `http` urls
  wp_api/src/login/url_discovery.rs
  wp_api_integration_tests/tests/test_login_immut.rs
Labels: Rust, Login

#544 Retrieve `/templates` endpoint
  wp_api/src/request/endpoint/templates_endpoint.rs
  wp_api/src/templates.rs
  wp_api_integration_tests/src/lib.rs
  wp_api_integration_tests/tests/test_templates_immut.rs
Labels: Rust, Endpoint, Testing

#550 Introduce `WpGmtDateTime`
  Cargo.lock
  native/kotlin/api/kotlin/src/integrationTest/kotlin/DateConversionTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/PostsEndpointTest.kt
  native/kotlin/api/kotlin/src/integrationTest/kotlin/TestCredentials.kt
  scripts/setup-test-site.sh
  wp_api/Cargo.toml
  wp_api/src/date.rs
  wp_api/src/lib.rs
  wp_api/src/posts.rs
  wp_api/src/request/endpoint/posts_endpoint.rs
  wp_api/src/unit_test_common.rs
  wp_api/src/url_query.rs
  wp_api/uniffi.toml
  wp_api_integration_tests/src/lib.rs
  wp_api_integration_tests/tests/test_posts_immut.rs
  wp_api_integration_tests/tests/test_posts_mut.rs
  wp_serde_helper/Cargo.toml
  wp_serde_helper/src/lib.rs
  wp_serde_helper/src/wp_serde_date.rs
Labels: Kotlin, Rust, Testing

#552 Handle parsing `[]` for `WpApiDetails.authentication` field
  wp_api/src/login.rs
  wp_api/src/login/url_discovery.rs
  wp_api_integration_tests/tests/test_login_err.rs
  wp_api_integration_tests/tests/test_login_immut.rs
Labels: Rust, Login

#553 Parsing error if `wp_derive::WpDeserialize` is combined with `#[serde(transparent)]`
  wp_derive/src/wp_deserialize.rs
  wp_derive/tests/fail/serde_transparent.rs
  wp_derive/tests/fail/serde_transparent.stderr
Labels: Rust

#554 Adds `AutoDiscoveryAttemptFailure::ApplicationPasswordsNotSupported`
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api_integration_tests/tests/test_login_err.rs
  wp_api_integration_tests/tests/test_login_immut.rs
Labels: Rust, Testing, Login

#556 Adds `test_gmt_date_time_from_time_stamp`
  wp_api/src/date.rs
Labels: Rust, Testing

#564 Update crate `convert_case` to `0.7.1`
  Cargo.lock
  Cargo.toml
Labels: Rust, dependency

#568 Update crate `thiserror` to `2.0.11`
  Cargo.lock
  Cargo.toml
Labels: Rust, dependency

#567 Update crates `strum` & `strum_macros` to `0.27.1`
  Cargo.lock
  Cargo.toml
Labels: Rust, dependency

#566 Update crate `rstest` to `0.24.0`
  Cargo.lock
  Cargo.toml
Labels: Rust, dependency

#565 Update crate `parse_link_header` to `0.4.0`
  Cargo.lock
  Cargo.toml
Labels: Rust, dependency

#569 Move `WpDeserialize` parser tests to `wp_deserialize` folder
  wp_derive/tests/parser_tests.rs
  wp_derive/tests/wp_deserialize/fail/non_optional_field.rs
  wp_derive/tests/wp_deserialize/fail/non_optional_field.stderr
  wp_derive/tests/wp_deserialize/fail/serde_transparent.rs
  wp_derive/tests/wp_deserialize/fail/serde_transparent.stderr
  wp_derive/tests/wp_deserialize/pass/basic_wp_deserialize.rs
Labels: Rust, Testing

#572 Move Login Application Errors to Rust
  wp_api/src/login/login_client.rs
  wp_api/src/login/url_discovery.rs
  wp_api/src/parsed_url.rs
Labels: Error Handling, Login

#583 Use `WpGmtDateTime` for all endpoints
  wp_api/src/comments.rs
  wp_api/src/date.rs
  wp_api/src/media.rs
  wp_api/src/posts.rs
  wp_api/src/request/endpoint/comments_endpoint.rs
  wp_api/src/request/endpoint/media_endpoint.rs
  wp_api/src/url_query.rs
  wp_api_integration_tests/tests/test_comments_immut.rs
  wp_api_integration_tests/tests/test_comments_mut.rs
  wp_api_integration_tests/tests/test_media_immut.rs
  wp_api_integration_tests/tests/test_media_mut.rs
  wp_api_integration_tests/tests/test_posts_mut.rs
Labels: Rust, Testing

#574 Localization support
  .buildkite/download-xcframework.sh
  .buildkite/pipeline.yml
  .swiftlint.yml
  Cargo.lock
  Cargo.toml
  fastlane/Fastfile
  native/kotlin/api/kotlin/src/integrationTest/kotlin/LocalizationTest.kt
  native/kotlin/build.gradle.kts
  wp_api/Cargo.toml
  wp_api/src/login/url_discovery.rs
  wp_localization/Cargo.toml
  wp_localization/localization/en-US/main.ftl
  wp_localization/localization/tr-TR/main.ftl
  wp_localization/src/lib.rs
  wp_localization/uniffi.toml
  wp_localization_macro/Cargo.toml
  wp_localization_macro/build.rs
  wp_localization_macro/src/lib.rs
  wp_localization_macro/src/wp_derive_localizable.rs
  wp_localization_macro/src/wp_messages.rs
Labels: Kotlin, Rust, Localization

#584 Add HTTP Header Parsing Helpers
  .clippy.toml
  wp_api/src/api_error.rs
  wp_api/src/request.rs
Labels: Error Handling
